// Auto generated for nvim v0.10.4
// See bin/generate_autocmds.py

enum NvimAutoCommandEvent: String {
  case bufadd
  case bufdelete
  case bufenter
  case buffilepost
  case buffilepre
  case bufhidden
  case bufleave
  case bufmodifiedset
  case bufnew
  case bufnewfile
  case bufreadcmd
  case bufreadpost
  case bufreadpre
  case bufunload
  case bufwinenter
  case bufwinleave
  case bufwipeout
  case bufwritecmd
  case bufwritepost
  case bufwritepre
  case chaninfo
  case chanopen
  case cmdundefined
  case cmdwinenter
  case cmdwinleave
  case cmdlinechanged
  case cmdlineenter
  case cmdlineleave
  case colorscheme
  case colorschemepre
  case completechanged
  case completedone
  case completedonepre
  case cursorhold
  case cursorholdi
  case cursormoved
  case cursormovedi
  case diagnosticchanged
  case diffupdated
  case dirchanged
  case dirchangedpre
  case encodingchanged
  case exitpre
  case fileappendcmd
  case fileappendpost
  case fileappendpre
  case filechangedro
  case filechangedshell
  case filechangedshellpost
  case filereadcmd
  case filereadpost
  case filereadpre
  case filetype
  case filewritecmd
  case filewritepost
  case filewritepre
  case filterreadpost
  case filterreadpre
  case filterwritepost
  case filterwritepre
  case focusgained
  case focuslost
  case funcundefined
  case guienter
  case guifailed
  case insertchange
  case insertcharpre
  case insertenter
  case insertleave
  case insertleavepre
  case lspattach
  case lspdetach
  case lspnotify
  case lspprogress
  case lsprequest
  case lsptokenupdate
  case menupopup
  case modechanged
  case optionset
  case quickfixcmdpost
  case quickfixcmdpre
  case quitpre
  case recordingenter
  case recordingleave
  case remotereply
  case safestate
  case searchwrapped
  case sessionloadpost
  case sessionwritepost
  case shellcmdpost
  case shellfilterpost
  case signal
  case sourcecmd
  case sourcepost
  case sourcepre
  case spellfilemissing
  case stdinreadpost
  case stdinreadpre
  case swapexists
  case syntax
  case tabclosed
  case tabenter
  case tableave
  case tabnew
  case tabnewentered
  case termchanged
  case termclose
  case termenter
  case termleave
  case termopen
  case termrequest
  case termresponse
  case textchanged
  case textchangedi
  case textchangedp
  case textchangedt
  case textyankpost
  case uienter
  case uileave
  case user
  case vimenter
  case vimleave
  case vimleavepre
  case vimresized
  case vimresume
  case vimsuspend
  case winclosed
  case winenter
  case winleave
  case winnew
  case winresized
  case winscrolled
}
