#!/usr/bin/env ruby
# encoding: utf-8

require 'pathname'
require 'optparse'

###### AppleScripts
newWindowScript = <<FIN
tell application id "com.qvacua.VimR"
  activate
  openFilesInNewWindow {#FILES}
end tell
FIN

frontmostWindowScript = <<FIN
tell application id "com.qvacua.VimR"
  activate
  if the (count of windows) ≥ 1 then
    openFilesInFrontmostWindow {#FILES} to the front window
  else
    openFilesInNewWindow {#FILES}
  end if
end tell
FIN

newWindowsScript = <<FIN
tell application id "com.qvacua.VimR"
  activate
  openFilesInNewWindows {#FILES}
end tell
FIN

goToLineScript = <<FIN
tell application id "com.qvacua.VimR"
  activate
  goToLine #LINE of #FILE
end tell
FIN

###### Helpers
def absolutePathsFromArgv()
  files = []
  ARGV.each do |f|
    if File.exist?(File.expand_path(f)) then
      files << "\"#{Pathname.new(f).realpath.to_s}\""
    else
      if f.start_with?('/')
        files << "\"#{f}\""
      else
        files << "\"#{Dir.pwd + '/' + f}\""
      end
    end
  end

  return files
end

def callOsaScript(script)
  return `/usr/bin/osascript -e '#{script.gsub(/#FILES/, absolutePathsFromArgv().join(','))}'`
end

###### Option handling
options = {
    :one_new_window => false,
    :multiple_new_window => false,
    :line => 0
}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: vimr [options] file1 file2 ..."

  opts.on('-n', '--new-window', 'open files in one new window') do
    options[:one_new_window] = true
  end

  opts.on('-m', '--multiple-window', 'open files in new windows') do
    options[:multiple_new_window] = true
  end

  opts.on('-l line', '--line line', Integer, 'go to line (> 0)') do |line|
   options[:line] = line
  end

  opts.on('-h', '--help', 'Displays Help') do
    puts "By default files are open in tabs in the front most window. If there's no open window, VimR will open a new window."
    puts opts
    exit
  end
end

parser.parse!

###### Do things
if options[:line] > 0
  `/usr/bin/osascript -e '#{goToLineScript.gsub(/#LINE/, "#{options[:line]}").gsub(/#FILE/, absolutePathsFromArgv()[0])}'`
  exit
end

if options[:one_new_window]
  callOsaScript(newWindowScript)
  exit
end

if options[:multiple_new_window]
  callOsaScript(newWindowsScript)
  exit
end

callOsaScript(frontmostWindowScript)
exit
