/**
 * Tae Won Ha - http://taewon.de - @hataewon
 * See LICENSE
 */

import Foundation
import ShortcutRecorder

let defaultShortcuts: [String: Shortcut?] = [
  "com.qvacua.vimr.menuitems.edit.copy": Shortcut(keyEquivalent: "⌘C"),
  "com.qvacua.vimr.menuitems.edit.cut": Shortcut(keyEquivalent: "⌘X"),
  "com.qvacua.vimr.menuitems.edit.delete": Shortcut(keyEquivalent: ""),
  "com.qvacua.vimr.menuitems.edit.paste": Shortcut(keyEquivalent: "⌘V"),
  "com.qvacua.vimr.menuitems.edit.redo": Shortcut(keyEquivalent: "⇧⌘Z"),
  "com.qvacua.vimr.menuitems.edit.select-all": Shortcut(keyEquivalent: "⌘A"),
  "com.qvacua.vimr.menuitems.edit.undo": Shortcut(keyEquivalent: "⌘Z"),
  "com.qvacua.vimr.menuitems.file.close": Shortcut(keyEquivalent: "⌘W"),
  "com.qvacua.vimr.menuitems.file.close-window": Shortcut(keyEquivalent: "⇧⌘W"),
  "com.qvacua.vimr.menuitems.file.new": Shortcut(keyEquivalent: "⌘N"),
  "com.qvacua.vimr.menuitems.file.new-tab": Shortcut(keyEquivalent: "⌘T"),
  "com.qvacua.vimr.menuitems.file.open-in-new-window": Shortcut(keyEquivalent: "⌥⌘O"),
  "com.qvacua.vimr.menuitems.file.open-quickly": Shortcut(keyEquivalent: "⇧⌘O"),
  "com.qvacua.vimr.menuitems.file.open": Shortcut(keyEquivalent: "⌘O"),
  "com.qvacua.vimr.menuitems.file.save-as": Shortcut(keyEquivalent: "⇧⌘S"),
  "com.qvacua.vimr.menuitems.file.save": Shortcut(keyEquivalent: "⌘S"),
  "com.qvacua.vimr.menuitems.help.vimr-help": Shortcut(keyEquivalent: ""),
  "com.qvacua.vimr.menuitems.tools.focus-neovim-view": Shortcut(keyEquivalent: "⌘."),
  "com.qvacua.vimr.menuitems.tools.toggle-all-tools": Shortcut(keyEquivalent: "⌘\\"),
  "com.qvacua.vimr.menuitems.tools.toggle-file-browser": Shortcut(keyEquivalent: "⌘1"),
  "com.qvacua.vimr.menuitems.tools.toggle-buffer-list": Shortcut(keyEquivalent: "⌘2"),
  "com.qvacua.vimr.menuitems.tools.toggle-markdown-preview": Shortcut(keyEquivalent: "⌘3"),
  "com.qvacua.vimr.menuitems.tools.toggle-html-preview": Shortcut(keyEquivalent: "⌘4"),
  "com.qvacua.vimr.menuitems.tools.toggle-tool-buttons": Shortcut(keyEquivalent: "⇧⌘\\"),
  "com.qvacua.vimr.menuitems.view.enter-full-screen": Shortcut(keyEquivalent: "⌃⌘F"),
  "com.qvacua.vimr.menuitems.view.font.bigger": Shortcut(keyEquivalent: "⌘+"),
  "com.qvacua.vimr.menuitems.view.font.reset-to-default-size": Shortcut(keyEquivalent: "⌘0"),
  "com.qvacua.vimr.menuitems.view.font.smaller": Shortcut(keyEquivalent: "⌘-"),
  "com.qvacua.vimr.menuitems.window.bring-all-to-front": Shortcut(keyEquivalent: ""), 
  "com.qvacua.vimr.menuitems.window.minimize": Shortcut(keyEquivalent: "⌘M"),
  "com.qvacua.vimr.menuitems.window.zoom": Shortcut(keyEquivalent: ""),
]

let legacyDefaultShortcuts: [String: [String: Any]] = [
  "com.qvacua.vimr.menuitems.edit.copy": [
    SRShortcutCharacters: "c",
    SRShortcutCharactersIgnoringModifiers: "c",
    SRShortcutKeyCode: 8,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.edit.cut": [
    SRShortcutCharacters: "x",
    SRShortcutCharactersIgnoringModifiers: "x",
    SRShortcutKeyCode: 7,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.edit.delete": [String: Any](),
  "com.qvacua.vimr.menuitems.edit.paste": [
    SRShortcutCharacters: "v",
    SRShortcutCharactersIgnoringModifiers: "v",
    SRShortcutKeyCode: 9,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.edit.redo": [
    SRShortcutCharacters: "z",
    SRShortcutCharactersIgnoringModifiers: "Z",
    SRShortcutKeyCode: 6,
    SRShortcutModifierFlagsKey: 1179914,
  ],
  "com.qvacua.vimr.menuitems.edit.select-all": [
    SRShortcutCharacters: "a",
    SRShortcutCharactersIgnoringModifiers: "a",
    SRShortcutKeyCode: 0,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.edit.undo": [
    SRShortcutCharacters: "z",
    SRShortcutCharactersIgnoringModifiers: "z",
    SRShortcutKeyCode: 6,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.file.close": [
    SRShortcutCharacters: "w",
    SRShortcutCharactersIgnoringModifiers: "w",
    SRShortcutKeyCode: 13,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.file.close-window": [
    SRShortcutCharacters: "w",
    SRShortcutCharactersIgnoringModifiers: "W",
    SRShortcutKeyCode: 13,
    SRShortcutModifierFlagsKey: 1179914,
  ],
  "com.qvacua.vimr.menuitems.file.new": [
    SRShortcutCharacters: "n",
    SRShortcutCharactersIgnoringModifiers: "n",
    SRShortcutKeyCode: 45,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.file.new-tab": [
    SRShortcutCharacters: "t",
    SRShortcutCharactersIgnoringModifiers: "t",
    SRShortcutKeyCode: 17,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.file.open-in-new-window": [
    SRShortcutCharacters: "ø",
    SRShortcutCharactersIgnoringModifiers: "o",
    SRShortcutKeyCode: 31,
    SRShortcutModifierFlagsKey: 1573160,
  ],
  "com.qvacua.vimr.menuitems.file.open-quickly": [
    SRShortcutCharacters: "o",
    SRShortcutCharactersIgnoringModifiers: "O",
    SRShortcutKeyCode: 31,
    SRShortcutModifierFlagsKey: 1179914,
  ],
  "com.qvacua.vimr.menuitems.file.open": [
    SRShortcutCharacters: "o",
    SRShortcutCharactersIgnoringModifiers: "o",
    SRShortcutKeyCode: 31,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.file.save-as": [
    SRShortcutCharacters: "s",
    SRShortcutCharactersIgnoringModifiers: "S",
    SRShortcutKeyCode: 1,
    SRShortcutModifierFlagsKey: 1179914,
  ],
  "com.qvacua.vimr.menuitems.file.save": [
    SRShortcutCharacters: "s",
    SRShortcutCharactersIgnoringModifiers: "s",
    SRShortcutKeyCode: 1,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.help.vimr-help": [String: Any](),
  "com.qvacua.vimr.menuitems.tools.focus-neovim-view": [
    SRShortcutCharacters: ".",
    SRShortcutCharactersIgnoringModifiers: ".",
    SRShortcutKeyCode: 47,
    SRShortcutModifierFlagsKey: 1048576,
  ],
  "com.qvacua.vimr.menuitems.tools.toggle-all-tools": [
    SRShortcutCharacters: "\\",
    SRShortcutCharactersIgnoringModifiers: "\\",
    SRShortcutKeyCode: 42,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.tools.toggle-file-browser": [
    SRShortcutCharacters: "1",
    SRShortcutCharactersIgnoringModifiers: "1",
    SRShortcutKeyCode: 18,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.tools.toggle-buffer-list": [
    SRShortcutCharacters: "1",
    SRShortcutCharactersIgnoringModifiers: "2",
    SRShortcutKeyCode: 19,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.tools.toggle-markdown-preview": [
    SRShortcutCharacters: "1",
    SRShortcutCharactersIgnoringModifiers: "3",
    SRShortcutKeyCode: 20,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.tools.toggle-html-preview": [
    SRShortcutCharacters: "1",
    SRShortcutCharactersIgnoringModifiers: "4",
    SRShortcutKeyCode: 21,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.tools.toggle-tool-buttons": [
    SRShortcutCharacters: "\\",
    SRShortcutCharactersIgnoringModifiers: "|",
    SRShortcutKeyCode: 42,
    SRShortcutModifierFlagsKey: 1179914,
  ],
  "com.qvacua.vimr.menuitems.view.enter-full-screen": [
    SRShortcutCharacters: "\006",
    SRShortcutCharactersIgnoringModifiers: "f",
    SRShortcutKeyCode: 3,
    SRShortcutModifierFlagsKey: 1319176,
  ],
  "com.qvacua.vimr.menuitems.view.font.bigger": [
    SRShortcutCharacters: "=",
    SRShortcutCharactersIgnoringModifiers: "=",
    SRShortcutKeyCode: 24,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.view.font.reset-to-default-size": [
    SRShortcutCharacters: "0",
    SRShortcutCharactersIgnoringModifiers: "0",
    SRShortcutKeyCode: 29,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.view.font.smaller": [
    SRShortcutCharacters: "-",
    SRShortcutCharactersIgnoringModifiers: "-",
    SRShortcutKeyCode: 27,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.window.bring-all-to-front": [String: Any](),
  "com.qvacua.vimr.menuitems.window.minimize": [
    SRShortcutCharacters: "m",
    SRShortcutCharactersIgnoringModifiers: "m",
    SRShortcutKeyCode: 46,
    SRShortcutModifierFlagsKey: 1048840,
  ],
  "com.qvacua.vimr.menuitems.window.zoom": [String: Any](),
]
